// API
export const REQUEST_ALL_GREEKS = 'REQUEST_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS = 'RECEIVE_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS_FAILURE = 'RECEIVE_ALL_GREEKS_FAILURE';
export const REQUEST_FIGURE = 'REQUEST_FIGURE';
export const RECEIVE_FIGURE = 'RECEIVE_FIGURE';
export const RECEIVE_FIGURE_FAILURE = 'RECEIVE_FIGURE_FAILURE';
export const TRIGGER_EDIT_MODE = 'TRIGGER_EDIT_MODE';

// FORM
export const REQUEST_FIGURE_UPDATE = 'REQUEST_FIGURE_UPDATE';
export const RECEIVE_FIGURE_UPDATE = 'RECEIVE_FIGURE_UPDATE';
export const RECEIVE_FIGURE_UPDATE_FAILURE = 'RECEIVE_FIGURE_UPDATE_FAILURE';