// API
export const REQUEST_ALL_GREEKS = 'REQUEST_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS = 'RECEIVE_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS_FAILURE = 'RECEIVE_ALL_GREEKS_FAILURE';
export const REQUEST_FIGURE = 'REQUEST_FIGURE';
export const RECEIVE_FIGURE = 'RECEIVE_FIGURE';
export const TRIGGER_EDIT_MODE = 'TRIGGER_EDIT_MODE';
